### ISSUE TITLE
Get 2MASS photometry

### ISSUE THREAD

**Issue by kevincovey** [yourstm/GaiaClusterRot#1]
... for members of each cluster (crossmatching to Gaia catalog w/ TOPCAT)  (http://vizier.cfa.harvard.edu/viz-bin/VizieR?-source=II/246&-to=3)

**Comment by yourstm** [comment]
So to be more clear. I am crossmatching my list of RA and DEC with 2MASS (and eventually PanSTARRS), and then crossmatching THAT new list with GAIA? I'm just not sure what the benefit of crossmatching with GAIA is if we're graphing data from the 2MASS x-match.

**Comment by kevincovey** [comment]
Yes, we want to crossmatch to Gaia so that we have the parallax info available.  We need the parallax to calculate distance and then put each cluster in an absolute HR diagram -- without that correction, the cluster stars would be brighter or fainter based on their distance and we couldn't compare their sequences as well.  

So the goal is to get 1 file w/ Gaia data + 2MASS data + PanSTARRS data all rolled into one, so that you can make distance calibrated color-magnitude diagrams that involve optical and infrared colors.
